# Generated by Django 2.1.5 on 2019-01-28 04:30

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('teamxteam', models.BooleanField()),
                ('team_players', models.IntegerField()),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('when', models.DateTimeField()),
                ('game_type', models.IntegerField()),
                ('players', models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
