# Generated by Django 2.1.5 on 2019-01-30 22:53

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('teamxteam', models.BooleanField()),
                ('team_players', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('when_date', models.DateField()),
                ('when_time', models.TimeField()),
                ('game_type', models.IntegerField()),
                ('players_team1', models.ManyToManyField(related_name='players_team1', to=settings.AUTH_USER_MODEL)),
                ('players_team2', models.ManyToManyField(blank=True, related_name='players_team2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
