# Generated by Django 2.1.5 on 2019-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190204_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_chat',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
