# Generated by Django 2.1.5 on 2019-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190204_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='sem_titulo', max_length=80),
            preserve_default=False,
        ),
    ]
